apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm-prom-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  -matrix:
      generators:
      - git:
          repoURL: https://github.com/dhpup/kargo-helm-prom-stack.git
          revision: main
          files:
          - path: "config/listelements.yaml"
      - list:
          # elements: []
          elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: "kube-prometheus-stack-{{.name}}"
      annotations:
        kargo.akuity.io/authorized-stage: "kargo-helm-prom-stack:{{.stage}}"
    spec:
      destination:
        namespace: monitoring
        name: "{{.name}}"
      project: kargo-helm-prom-stack
      source:
        repoURL: https://github.com/dhpup/kargo-helm-prom-stack.git
        targetRevision: "env/{{.name}}"
        path: .
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
