apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-prom-stack
spec:
  project: kargo-helm-prom-stack
  source:
    repoURL: https://github.com/dhpup/kargo-helm-prom-stack.git
    path: kargo
  destination:
    name: kargo1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true