---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm-prom-stack:mac1
  name: kube-prometheus-stack-mac1
spec:
  destination:
    name: mac1
    namespace: monitoring
  project: kargo-helm-prom-stack
  source:
    path: .
    repoURL: https://github.com/dhpup/kargo-helm-prom-stack.git
    targetRevision: env/mac1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm-prom-stack:mac2
  name: kube-prometheus-stack-mac2
spec:
  destination:
    name: mac2
    namespace: monitoring
  project: kargo-helm-prom-stack
  source:
    path: .
    repoURL: https://github.com/dhpup/kargo-helm-prom-stack.git
    targetRevision: env/mac2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
